# Generated by Django 4.2.5 on 2023-11-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0002_loanmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='total_balance',
            field=models.BigIntegerField(null=True),
        ),
    ]
