# Generated by Django 4.2.5 on 2023-11-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0003_loanmodel_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.bankmodel'),
        ),
    ]
