# Generated by Django 4.2.5 on 2023-11-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0004_loanmodel_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='bank_acc_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='upi_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
