# Generated by Django 4.2.5 on 2023-11-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0005_loanmodel_bank_acc_number_loanmodel_cheque_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_value', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
