# Generated by Django 4.2.5 on 2023-11-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0006_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='duration',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
