# Generated by Django 4.2.5 on 2023-11-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vyaparapp', '0007_alter_loanmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vyaparapp.staff_details'),
        ),
    ]
